Change "Privacy Quiz" to "Anonymity Quiz"
techlore/website pull request #115
Opened 2024-07-10 14:42 UTC by 8pen-s8urce

This quiz is called "Anonimity Quiz", therefore the wording in techlore.tech should make that clear.

2024-07-11 01:12 UTC, JenniferR25 approved these changes
The title of ./spa.html is "Techlore | Anonymity Quiz", based on that, it seems the change from "Privacy" to "Anonymity" is appropriate and more accurately described the linked content.

2024-07-14 10:45 UTC, rollsicecream requested changes

2024-07-14 10:45 UTC, rollsicecream commented on index.html
> +                <a target="_self" href="./spa.html"> Anonimity Quiz </a>
There's a quick typo here: 

```suggestion
                <a target="_self" href="./spa.html"> Anonymity Quiz </a>
```

2024-07-14 14:24 UTC, JenniferR25 approved these changes

2024-07-14 16:01 UTC, rollsicecream approved these changes

2024-07-20 14:54 UTC, merged